### ISSUE TITLE
Invalid Taxonomy on Milestones for 1.26

### ISSUE THREAD

**Issue by oraclerob** [upstreamplugin/UpStream#880]
## Expected Behavior
When exporting (via full schema MySQL) from 1.25 to 1.26 clean database (tables are truncated) we should not see errors on the backend. The backend and frontend fail to work properly and cannot be used at all. 

## Current Behavior
The following fatal stack trace occurs.

PHP message: PHP Fatal error:  Uncaught UpStream\Exception: Invalid taxonomy. in /usr/share/nginx/html/dev1/wp-content/plugins/upstream/includes/admin/metaboxes/metabox-functions.php:1195
Stack trace:
#0 /usr/share/nginx/html/dev1/wp-content/plugins/upstream-frontend-edit/templates/add-milestone.php(36): upstream_admin_get_milestone_categories()
#1 /usr/share/nginx/html/dev1/wp-includes/template.php(722): require_once('/usr/share/ngin...')
#2 /usr/share/nginx/html/dev1/wp-content/plugins/upstream/includes/frontend/up-template-functions.php(31): load_template('/usr/share/ngin...')
#3 /usr/share/nginx/html/dev1/wp-content/plugins/upstream-frontend-edit/includes/class-up-frontend-output.php(683): upstream_get_template_part('add-milestone.p...')
#4 /usr/share/nginx/html/dev1/wp-includes/class-wp-hook.php(286): UpStream_Frontend_Output->modals('')
#5 /usr/share/nginx/html/dev1/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#6 /usr/share/nginx/html/dev1/wp-includes/plugin.php(465): WP_Hoo" while reading response header from upstream, client: 203.59.95.38, server: dev1.ifnc.com.au, request: "GET /projects/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/php-fpm.sock:", host: "dev1.ifnc.com.au", referrer: "https://dev1.ifnc.com.au/projects/"

## Context
We cannot reliably test that 1.26 is not going to break in production.

**Comment by stevejburge** [comment]
Thanks @oraclerob I've tagged this for a fix in 1.27

**Comment by oraclerob** [comment]
Still an issue in the 1.27.1 update.

**Comment by westbourneintl** [comment]
Hi @oraclerob -- do you have some data (or steps to create data) that you can send to reproduce this? I can't find a way to reproduce it

**Comment by oraclerob** [comment]
You will need to have a few custom taxomonies  (categories) on 1.25 and try to import to 1.26+ to replicate. I'm upgrading our customer to 1.27.2 this weekend so I'll see if it is still an issue.
